       SUBROUTINE UEXTERNALDB(LOP, LRESTART, TIME,
     1 DTIME, KSTEP, KINC)
	 
       INCLUDE 'ABA_PARAM.INC'
       DIMENSION TIME(2)
	  PARAMETER(NELE=6)
	  COMMON/EACHIN/DEEPEST
	  COMMON/WELABLE/WVECTOR(NELE)
	  COMMON/DALABLE/DVECTOR(NELE)
	  
	  IF (LOP.EQ.0) THEN
	   DVECTOR(:)=0.0D0
	   DEEPEST=0.0D0
	  END
	  IF (LOP.EQ.1) THEN
         DEEPEST=MINVAL(DVECTOR)
	  END
	  
	  return 
	  end
	  
